# Generated by Django 4.2 on 2024-11-15 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculateFee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='final_amount',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
