# Generated by Django 4.2 on 2024-11-15 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculateFee', '0002_order_final_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdetail',
            name='drink_id',
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='drink_image',
            field=models.ImageField(blank=True, upload_to='photos/drink/drinks/'),
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='drink_name',
            field=models.CharField(default='Unknown Drink', max_length=100),
        ),
        migrations.DeleteModel(
            name='drink',
        ),
    ]
